Merge my_develop/improve_install_script into: my_local/current_release
Squashed commit of the following:

commit 5d86e7e2b7f440bb451f27bd824e70e381251d79
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Sun Jan 22 19:57:24 2023 +0100

    Fixes renaming issue from IDE which killed the git rev sed command

commit 9b6799e7502ecb1f01afbebaadced08ce3573188
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Sun Jan 22 10:48:59 2023 +0100

    Fixes last issue with script (dl directory) some cosmetics ie. too much output and adds git_rev update TODO/Notes

commit ea8eba326b83988537d41c2a0b409e4bbc8bf4fa
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Sat Jan 21 10:31:18 2023 +0100

    Adds (untested yet) fix for uploads dir to only upload if there is anything (file or dir) in the directory

commit c347aa51d6e5a1a5a563927c99576a7daa8dbe3e
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Sat Jan 21 10:19:16 2023 +0100

    Updates clean up script to log out left over directories and files after clean up

commit 31db2e30e7e9768075c4ebde2b271a7c09c5adb3
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Fri Jan 20 15:18:01 2023 +0100

    Adds TODO and to be fixed issue

commit cfc1d0865d7ff9df3a4aa9650cf7e140468a5855
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Tue Jan 17 17:52:10 2023 +0100

    Fixes various issues in the script(s)

commit 639a0030fe274a0b21787b1c2215d121404202df
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Sun Jan 15 10:52:38 2023 +0100

    Adds check (safety but not very nice - yet) to prevent errors when GIT_REV constant doesn't exist

    Anyway. It's to be discussed/re-thought if this is really a constant or more a config value?! At the moment I would tend more to it being a config entry but not sure as it feels wrong too.

    But as the enviro version is also set there it should be ok!

commit b31ba31746aec39f684ba0817d65a35955f99ace
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Sun Jan 15 09:37:33 2023 +0100

    Adds and updates the installer script functionality

    - Do download logs and config
    - Do clean up the device prior to upload to be sure not to have leftover code parts or unwanted stuf laying around
    - Do upload a config per device via UID selected
    - Do add the current Git rev as constant to be logged and or sent by MQTT

commit 7fe388bb57659487abd38cb6d54e1ae5b2a3c48a
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Tue Jan 3 12:26:25 2023 +0100

    Updates script to do the config copy if available

commit 8fd32a5d215d5af9b6146de0d1e1a63a749d3e5e
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Tue Jan 3 12:16:32 2023 +0100

    Fixes one TODO and prepares directory for <uid>-config.py files per board (not version controlled!)

commit 4eb41770a3e31f5dd5e5c0f36d5ce31f69098925
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Tue Jan 3 12:06:43 2023 +0100

    Adds TODO's

commit 3413781e4d7998e817f102114516e5ce5ca6b9eb
Author: Pascal Kern <pkscal.kern@gmail.com>
Date:   Tue Jan 3 11:43:47 2023 +0100

    Updates script to create a constant (GIT_REV) when uploading include config.py (to be improved)

diff --git a/install-on-device-fs b/install-on-device-fs
--- a/install-on-device-fs
+++ b/install-on-device-fs
@@ -61,9 +61,9 @@ function update_git_rev() {
   echo -n "> Updating Git REV in constants"
   # TODO Nasty hack to get it work on MacOS AND Linux'. Remove by utilising a Docker image ie. bash image if needed
   if [[ "$OSTYPE" == "darwin"* ]]; then
-    sed -i '' -E "s/^(GIT_REV: str =).*/\1 '$rev'/" "${file/:/}"
+    sed -i '' -E "s/^(GIT_REV +=).*/\1 '$rev'/" "${file/:/}"
   else
-    sed -i -E "s/^(GIT_REV: str =).*/\1 '$rev'/" "${file/:/}"
+    sed -i -E "s/^(GIT_REV +=).*/\1 '$rev'/" "${file/:/}"
   fi
   echo_command_exit_code $?
 }
@@ -215,5 +215,16 @@ upload_actual_config $current_board_uid
 # if [ -z "$(ls -A "uploads/$current_board_uid" 2> dev/null)" ]; then
 if [ -z "$(find "uploads/$current_board_uid" -prune -empty  2> /dev/null)" ]; then
   create_directory uploads
-  copy "uploads/$current_board_uid/*.json" :uploads/
+  uploaded_postfix="uploaded"
+  if copy "uploads/$current_board_uid/*.json" :uploads/; then
+    echo -n "> removing old uploaded archive directory"
+    rm -rf "uploads/$current_board_uid $uploaded_postfix" > /dev/null
+    echo_command_exit_code $?
+    echo -n "> renaming uploads directory"
+    mv -f "uploads/$current_board_uid" "uploads/$current_board_uid $uploaded_postfix" > /dev/null
+    # rm -rf "uploads/$current_board_uid/*.json" > /dev/null
+    echo_command_exit_code $?
+  else
+    echo "> Failed to upload uploads! Keep them locally without renaming."
+  fi
 fi
