Adds and updates the installer script functionality
- Do download logs and config
- Do clean up the device prior to upload to be sure not to have leftover code parts or unwanted stuf laying around
- Do upload a config per device via UID selected
- Do add the current Git rev as constant to be logged and or sent by MQTT

diff --git a/install-on-device-fs b/install-on-device-fs
--- a/install-on-device-fs
+++ b/install-on-device-fs
@@ -78,12 +78,26 @@ function get_board_uid() {
 }
 
 function upload_actual_config() {
-  board_uid="${1:?"Must provide a UID as first argument"}"
-  act_config_file="configs/${board_uid}-config.py"
-  echo "> Copying actual config ($act_config_file) for this board"
+  act_config_file="configs/$(get_uid)-config.py"
+  echo -n "> Copying actual config for this board"
   if [ -f "$act_config_file" ]; then
-    copy "$act_config_file" :config.py
+    if copy "$act_config_file" :config.py; then
+      echo " .. done!"
+    else
+      echo " .. failed!"
+    fi
   else
+    echo " .. No config found for this board. Missing file: '$act_config_file'"
+  fi
+}
+
+function download() {
+  file="${1:?"Must specify a file to download from the remote filesystem!"}"
+  out_dir="${2:-"./"}"
+  out_file="$(date "+%Y-%m-%d_%H-%M-%S")-$(basename "$file")"
+  echo -n "> download file '$file' to: '$out_dir' as '$out_file'"
+  if [[ "." != "$out_dir" ]]; then
+    mkdir -p "$out_dir"
     echo " .. No config found for this board. Missing file: '$act_config_file'"
   fi
 }
@@ -166,6 +180,30 @@ function get_git_info() {
     branch="$(git branch --no-color 2> /dev/null | sed -e '/^[^*]/d' -e "s/* \(.*\)/\1$dirty/")"
     echo -n "$branch$hash_short"
   fi
+
+  echo_command_exit_code "$(mpremote connect ${DEVICE} cp "$file" "$out_dir/$out_file" > /dev/null)"
+  #if mpremote connect ${DEVICE} cp "$file" "$out_dir/$out_file" > /dev/null; then
+  #  echo " .. done!"
+  #else
+  #  echo " .. failed!"
+  #fi
+}
+
+function clean_up() {
+  echo "> Cleaning current content on device..."
+  # Would be nice to provide the dirs dynamically. But mpremote run seems not to pass on
+  # arguments to the script. Therefor the dirs to clean are hard coded in the python script!
+  files="main.py log.txt"
+  for file in $files; do
+    echo "> Removing '$file"
+    mpremote connect ${DEVICE} rm ":$file" 2&> /dev/null
+    echo_command_exit_code $?
+  done
+  echo "> Cleaning directories..."
+  mpremote connect ${DEVICE} run install_on_device_fs_helper.py
+  echo_command_exit_code $?
+  echo "> Cleaning done. Content still on the device is:"
+  mpremote connect ${DEVICE} ls :
 }
 
 function get_uid() {
@@ -179,6 +217,8 @@ current_git_rev="$(get_git_info)"
 
 echo "> Working with device: '$DEVICE' with the UID: '$current_board_uid' on Git rev: '$current_git_rev'"
 
+download ":log.txt" "./logs_dl/$current_uid"
+download ":config.py" "./configs/$current_uid"
 
 echo "> Downloading files...."
 
