Fixes last issue with script (dl directory) some cosmetics ie. too much output and adds git_rev update TODO/Notes

diff --git a/install-on-device-fs b/install-on-device-fs
--- a/install-on-device-fs
+++ b/install-on-device-fs
@@ -88,7 +88,7 @@ function upload_actual_config() {
   fi
 }
 
-function download() {
+function download_file() {
   file="${1:?"Must specify a file to download from the remote filesystem!"}"
   out_dir="${2:-"./"}"
   out_file="$(date "+%Y-%m-%d_%H-%M-%S")-$(basename "${file/:/}")"
@@ -186,11 +186,35 @@ function get_git_info() {
   error=$?
   if [[ "$result" == *"ENOENT"* ]]; then
     echo " .. does not exist (anymore)!"
-    rmdir -p "$out_dir"
+    rmdir -p "$out_dir" 2> /dev/null
     return 0
   else
     echo_command_exit_code $error
   fi
+}
+
+function download_dir() {
+  src_dir="${1:?"Must specify a directory to download from the remote filesystem!"}"
+  out_dir="${2:-"./"}"
+  echo "> download content of directory '$src_dir' to: '$out_dir'"
+  if [[ "." != "$out_dir" ]]; then
+    mkdir -p "$out_dir"
+  fi
+
+  files=$(mpremote connect ${DEVICE} ls "$src_dir" | awk '{print $2}' | sed -e '$d' | tr -d '\r')
+  if [ $? -ne 0 ]; then
+    echo "> failed to get content of dir: '$src_dir' for download. Aborting"
+    return 0
+  fi
+
+  echo $files > test.out
+
+  for fle in $files; do
+    echo -n "  copy '$fle'"
+    mpremote connect ${DEVICE} cp "$src_dir/$fle" "$out_dir/" > /dev/null
+    echo_command_exit_code $?
+  done
+
 }
 
 function clean_up() {
@@ -203,7 +227,7 @@ function clean_up() {
     mpremote connect ${DEVICE} rm ":$file" > /dev/null
     echo_command_exit_code $?
   done
-  echo -n "> Cleaning directories..."
+  echo "> Cleaning directories..."
   mpremote connect ${DEVICE} run install_on_device_fs_helper.py
   echo_command_exit_code $?
 }
@@ -236,9 +260,12 @@ current_git_rev="$(get_git_info)"
 
 echo "> Working with device: '$DEVICE' with the UID: '$current_board_uid' on Git rev: '$current_git_rev'"
 
-download ":log.txt" "./logs_dl/$current_board_uid"
-download ":config.py" "./configs/$current_board_uid"
-download ":uploads" "./uploads/$current_board_uid"
+
+echo "> Downloading files...."
+
+download_file ":log.txt" "./logs_dl/$current_board_uid"
+download_file ":config.py" "./configs/$current_board_uid"
+download_dir ":uploads" "./uploads/$current_board_uid"
 
 echo "> Downloading files...."
 
